import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import TheHeader from '@/app/components/theHeader/TheHeader';
import TheFooter from '@/app/components/theFooter/TheFooter';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          position: 'relative',
          display: 'flex',
          flexDirection: 'column',
          height: '100vh',
          justifyContent: 'space-between',
        }}
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <TheHeader />
        <main style={{ flex: 1 }}>{children}</main>
        <TheFooter />
      </body>
    </html>
  );
}
